### PR TITLE
Create binary_search_exe.c

### PR DESCRIPTION
**Pull request by NidhiNivedita6**
Sir, Please review this.

### CODE REVIEW

**Comment by RavinduSachintha** [comment]
your 

> Sir, Please review this.

your implementation is in good quality and we can merge it. however, didn't we assign you to an issue? If not we will have to create a new one.

**Comment by NidhiNivedita6** [comment]
Sir I was assigned this issue.

**Review by RavinduSachintha — APPROVED** [review]

**Comment by RavinduSachintha** [comment]
> Sir I was assigned this issue.

this is a pull request. I think we have missed it. Don't worry. I will create a new issue and link it to this.

**Comment by NidhiNivedita6** [comment]
Ok Sir

**Comment by RavinduSachintha** [comment]
@all-contributors please add @NidhiNivedita6 for code
Thank you for your contribution to this repository @NidhiNivedita6. Wish you good luck for hacktoberfest. :slightly_smiling_face: 
Make sure to star this repo :wink:

**Pull request merged**
