### PR TITLE
Added insertion sort in Go

### LINKED ISSUE #465: Insertion sort in Go
#### This issue is about [Algo/DS Name](link to resource for the Algo/DS)

-   [x] Issue Title is in form `[Algo/DS Name] in [Language]` (ex:- BubbleSort in Java)

-   [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate

-   [x] Assign this issue to me (I want to work on this)

   -   [x] I ensure that I am not already assigned to 2 or more issues
  
-   [x] I will send my PR only after I'm assigned to this issue by any maintainer

### PR DESCRIPTION
**Pull request by zinthanmm**
**Hi!**  
Thanks for considering contributing to this ever-growing list of algorithm and data structure implementations.
Your contribution is valuable. Use the follow template for creating Pull Requests
---

**Fixes #465 

By submitting this pull request I confirm I've read and complied with the below declarations.

-   [x] I have read the [Contribution guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md) 
and I am confident that my PR reflects them.

-   [x] I have followed the [coding guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#cs) 
for this project.

-   [x] My code follows the [skeleton code structure](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#sample).

-   [x] This pull request has a descriptive title. 
For example, `Added {Algorithm/DS name} [{Language}]`, not `Update README.md` or `Added new code`.

-   [x] This pull request shall only be merged once the build passes.

-   [x] I have mentioned the issue number correctly (with hyper-link) in this pull request description.

### CODE REVIEW

**Comment by RavinduSachintha** [comment]
@zinthanmm can you add this contribution to the algorithm chart in main readme file. Don't change anything else. 😄

**Comment by RavinduSachintha** [comment]
Push changes to this PR.

**Review by RavinduSachintha — APPROVED** [review]

**Comment by zinthanmm** [comment]
> @zinthanmm can you add this contribution to the algorithm chart in main readme file. Don't change anything else. 😄

readme file is already ticked for insertion sort in Go. Btw, please add hacktoberfest tag to this PR.

**Comment by RavinduSachintha** [comment]
> > @zinthanmm can you add this contribution to the algorithm chart in main readme file. Don't change anything else. 😄
> 
> readme file is already ticked for insertion sort in Go. Btw, please add hacktoberfest tag to this PR.

Sry. My mistake. I will add the tag and merge this PR. Thank you for your contribution. 👍

**Comment by zinthanmm** [comment]
> > > @zinthanmm can you add this contribution to the algorithm chart in main readme file. Don't change anything else. 😄
> > 
> > 
> > readme file is already ticked for insertion sort in Go. Btw, please add hacktoberfest tag to this PR.
> 
> Sry. My mistake. I will add the tag and merge this PR. Thank you for your contribution. 👍

No worries. Pleasure for being able to contribute.  👍

**Comment by RavinduSachintha** [comment]
@all-contributors please add @zinthanmm for code too.

**Pull request merged**
