### PR TITLE
Added Selection Sort in cpp

### PR DESCRIPTION
**Pull request by venturo-raj7**
**Hi!**  
Thanks for considering for contributing to this ever-growing list of algorithm and data structure implementations.
Your contribution is valuable. Use the follow template for creating PRs. (Delete this part)
---

**Fixes #646 **

By submitting this pull request I confirm I've read and complied with the below declarations.

-   [x] I have read the [Contribution guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md) 
and I am confident that my PR reflects them.

-   [x] I have followed the [coding guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#cs) 
for this project.

-   [ ] My code follows the [skeleton code structure](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#sample).

-   [ ] This pull request has a descriptive title. 
For example, `Added {Algorithm/DS name} [{Language}]`, not `Update README.md` or `Added new code`.

-   [ ] This pull request shall only be merged once the build passes.

-   [x] I have mentioned the issue number correctly (with hyper-link) in this pull request description.

### CODE REVIEW

**Comment by RavinduSachintha** [comment]
@venturo-raj7 you have to change the filename with the correct convention. please check it from the contributing doc. after that you can add this contribution to the algorithm chart on readme file. don't change anything else. :+1:

**Comment by venturo-raj7** [comment]
how to add this contribution to algorithm chart please guide me through i m new to this

**Comment by RavinduSachintha** [comment]
> how to add this contribution to algorithm chart please guide me through i m new to this

before that, you should change the filename correctly. please read the contribution doc.

**Comment by Danushka96** [comment]
Hi @venturo-raj7 
Open the main Readme.md file and check how to add a tick to an MD file and add it to the algorithm you implemented in the table, 
Thanks

**Comment by venturo-raj7** [comment]
> > how to add this contribution to algorithm chart please guide me through i m new to this
> 
> before that, you should change the filename correctly. please read the contribution doc.

I have changed sir please check

**Comment by venturo-raj7** [comment]
> > how to add this contribution to algorithm chart please guide me through i m new to this
> 
> before that, you should change the filename correctly. please read the contribution doc.

Sir please check it and merge it so that I can work on my other pull requests

**Comment by RavinduSachintha** [comment]
> I have changed sir please check

You need to change the file name, not the PR or issue title. According to the contribution guidelines, for C++ language, the filename should only be contained simple letters and underscore. (spaces are invalid)

**Comment by RavinduSachintha** [comment]
> > I have changed sir please check
> 
> You need to change the file name, not the PR or issue title. According to the contribution guidelines, for C++ language, the filename should only be contained simple letters and underscore. (spaces are invalid)

We will not be able to go further until you fix the assigned issue properly. Thank you.

**Comment by venturo-raj7** [comment]
> > > I have changed sir please check
> > 
> > 
> > You need to change the file name, not the PR or issue title. According to the contribution guidelines, for C++ language, the filename should only be contained simple letters and underscore. (spaces are invalid)
> 
> We will not be able to go further until you fix the assigned issue properly. Thank you.

i have changed file name also please check and guide me if there are any more changes that should be made by far i have done everything i dont suppose anything else is left please see

**Pull request closed without merging**
