### PR TITLE
Create implementation.c

### LINKED ISSUE #702: Linked list implementation in C
#### This issue is about [Algo/DS Name](link to resource for the Algo/DS)

-   [ ] Issue Title is in form `[Algo/DS Name] in [Language]` (ex:- BubbleSort in Java)

-   [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate

-   [ ] Assign this issue to me (I want to work on this)

   -   [ ] I ensure that I am not already assigned to 2 or more issues
  
-   [ ] I will send my PR only after I'm assigned to this issue by any maintainer

### PR DESCRIPTION
**Pull request by aditisneh**
**Fixes #702 **

By submitting this pull request I confirm I've read and complied with the below declarations.

-   [x] I have read the [Contribution guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md) 
and I am confident that my PR reflects them.

-   [x] I have followed the [coding guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#cs) 
for this project.

-   [x] My code follows the [skeleton code structure](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#sample).

-   [x] This pull request has a descriptive title. 
For example, `Added {Algorithm/DS name} [{Language}]`, not `Update README.md` or `Added new code`.

-   [x] This pull request shall only be merged once the build passes.

-   [x] I have mentioned the issue number correctly (with hyper-link) in this pull request description.

### CODE REVIEW

**Review by Danushka96 — APPROVED** [review]

**Comment by Danushka96** [comment]
Hi @aditisneh 
Can update the main Readme.md file with the data structure you implemented,
Just update the file and send the commit to this PR, 
Thanks

**Comment by aditisneh** [comment]
> Hi @aditisneh
> Can update the main Readme.md file with the data structure you implemented,
> Just update the file and send the commit to this PR,
> Thanks

Done, Thanks for assigning me this issue.

**Comment by Danushka96** [comment]
@all-contributors please add @aditisneh  for code and doc

**Comment by Danushka96** [comment]
Hi @aditisneh 
Thanks for your contribution!

**Pull request merged**
