### PR TITLE
Added DFS Graph Algorithm in C

### LINKED ISSUE #487: Depth First Search in C
This is an open issue for the Depth First Search algorithm implementation in C. If you wish to contribute, just make some noise and we will assign you.

### PR DESCRIPTION
**Pull request by KoushikSahu**
**Fixes #487**

By submitting this pull request I confirm I've read and complied with the below declarations.

-   [x] I have read the [Contribution guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md) 
and I am confident that my PR reflects them.

-   [x] I have followed the [coding guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#cs) 
for this project.

-   [x] My code follows the [skeleton code structure](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#sample).

-   [x] This pull request has a descriptive title. 
For example, `Added {Algorithm/DS name} [{Language}]`, not `Update README.md` or `Added new code`.

-   [x] This pull request shall only be merged once the build passes.

-   [x] I have mentioned the issue number correctly (with hyper-link) in this pull request description.

### CODE REVIEW

**Review by Danushka96 — APPROVED** [review]

**Comment by Danushka96** [comment]
Hi @KoushikSahu 
Can you add the algorithm to the main Readme.md file? just add a tick and send the commit to this PR.

**Comment by KoushikSahu** [comment]
> Hi @KoushikSahu
> Can you add the algorithm to the main Readme.md file? just add a tick and send the commit to this PR.

Sure

**Comment by Danushka96** [comment]
@all-contributors please add @KoushikSahu for code and doc

**Comment by Danushka96** [comment]
@KoushikSahu Thanks for your contribution, Keep it up.

**Pull request merged**
