### PR TITLE
Added MergeSort with GoLang

### LINKED ISSUE #389: Merge Sort in Golang
This issue is about Merge Sort in Golang.

### PR DESCRIPTION
**Pull request by mertbarutcuoglu**
**Fixes #389**

### CODE REVIEW

**Comment by mertbarutcuoglu** [comment]
Hi @RavinduSachintha! Can we close this if it is okay?

**Review by RavinduSachintha — APPROVED** [review]

**Comment by RavinduSachintha** [comment]
> Hi @RavinduSachintha! Can we close this if it is okay?

@mertbarutcuoglu sorry for the delay. we got some problems with the validation system for golang and now we have fixed it. Would you be able to add this contribution to the algorithm chart on the main readme file? Don't change anything else. you just need to make the change and push it.

**Comment by mertbarutcuoglu** [comment]
> > Hi @RavinduSachintha! Can we close this if it is okay?
> 
> @mertbarutcuoglu sorry for the delay. we got some problems with the validation system for golang and now we have fixed it. Would you be able to add this contribution to the algorithm chart on the main readme file? Don't change anything else. you just need to make the change and push it.

Sure!

**Comment by RavinduSachintha** [comment]
@all-contributors please add @mertbarutcuoglu for code and doc

**Comment by RavinduSachintha** [comment]
@mertbarutcuoglu Thank you for your contribution. Keep it up. :+1:  And make sure to star this repo :wink:

**Comment by mertbarutcuoglu** [comment]
@RavinduSachintha will do, thanks!

**Pull request merged**
