### PR TITLE
added lcs in python3

### LINKED ISSUE #785: Longest Common Subsequence in Python3
This is an open issue for the Longest Common Subsequence algorithm implementation in Python3. If you wish to contribute, just make some noise and we will assign you.

### PR DESCRIPTION
**Pull request by gpk2000**
**Fixes #785**

By submitting this pull request I confirm I've read and complied with the below declarations.

-   [X] I have read the [Contribution guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md) 
and I am confident that my PR reflects them.

-   [X] I have followed the [coding guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#cs) 
for this project.

-   [X] My code follows the [skeleton code structure](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#sample).

-   [X] This pull request has a descriptive title. 
For example, `Added {Algorithm/DS name} [{Language}]`, not `Update README.md` or `Added new code`.

-   [X] This pull request shall only be merged once the build passes.

-   [X] I have mentioned the issue number correctly (with hyper-link) in this pull request description.

### CODE REVIEW

**Comment by Danushka96** [comment]
Hi @gpk2000 
Please read the guideline for proper naming conversion

**Comment by gpk2000** [comment]
I just followed the naming convention in the Java code
Screenshot from 2020-10-27 18-39-27

**Comment by Danushka96** [comment]
But this is python, right?

**Review by Danushka96 — APPROVED** [review]

**Comment by Danushka96** [comment]
@all-contributors please add @gpk2000 for code and doc

**Comment by Danushka96** [comment]
Hi @gpk2000 
Thanks for your contribution!

**Pull request merged**
