### PR TITLE
Add Largest Sum Contiguous Subarray in Go

### LINKED ISSUE #728: Largest Sum Contiguous Sub-Array in Golang
This is an open issue for the Largest Sum Contiguous Sub-Array algorithm implementation in Golang. If you wish to contribute, just make some noise and we will assign you.

### PR DESCRIPTION
**Pull request by bmpj13**
**Fixes #728 **

By submitting this pull request I confirm I've read and complied with the below declarations.

-   [x] I have read the [Contribution guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md) 
and I am confident that my PR reflects them.

-   [x] I have followed the [coding guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#cs) 
for this project.

-   [x] My code follows the [skeleton code structure](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#sample).

-   [x] This pull request has a descriptive title. 
For example, `Added {Algorithm/DS name} [{Language}]`, not `Update README.md` or `Added new code`.

-   [x] This pull request shall only be merged once the build passes.

-   [x] I have mentioned the issue number correctly (with hyper-link) in this pull request description.

### CODE REVIEW

**Comment by Danushka96** [comment]
Hi @bmpj13 
Can you update the main Readme.md file algorithm chart with the algorithm you implemented,
Send the commit to this PR,
Thanks

**Comment by bmpj13** [comment]
> Hi @bmpj13
> Can you update the main Readme.md file algorithm chart with the algorithm you implemented,
> Send the commit to this PR,
> Thanks

@Danushka96 done

**Review by RavinduSachintha — APPROVED** [review]

**Comment by RavinduSachintha** [comment]
@all-contributors please add @bmpj13 for code and doc

**Comment by RavinduSachintha** [comment]
@bmpj13 thank you for your contribution. keep it up :+1:  and make sure to star this repo :wink:

**Pull request merged**
