### PR TITLE
Add bubble sort in charp to readme as well

### LINKED ISSUE #485: Bubble Sort in C#
This is an open issue for the Bubble Sort algorithm implementation in C#. If you wish to contribute, just make some noise and we will assign you.

### PR DESCRIPTION
**Pull request by forsas**
**Hi!**  
Thanks for considering for contributing to this ever-growing list of algorithm and data structure implementations.
Your contribution is valuable. Use the follow template for creating PRs. (Delete this part)
---

**Fixes #485 **

By submitting this pull request I confirm I've read and complied with the below declarations.

-   [ x] I have read the [Contribution guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md) 
and I am confident that my PR reflects them.

-   [x ] I have followed the [coding guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#cs) 
for this project.

-   [ x] My code follows the [skeleton code structure](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#sample).

-   [ x] This pull request has a descriptive title. 
For example, `Added {Algorithm/DS name} [{Language}]`, not `Update README.md` or `Added new code`.

-   [ x] This pull request shall only be merged once the build passes.

-   [ x] I have mentioned the issue number correctly (with hyper-link) in this pull request description.

### CODE REVIEW

**Comment by forsas** [comment]
https://github.com/FOSS-UCSC/FOSSALGO/pull/503

**Review by Danushka96 — APPROVED** [review]

**Comment by Danushka96** [comment]
Hi @forsas 
This PR is only contain the Readme update, you have closed the previous PR too, Can you add the C# code for this PR?

**Comment by forsas** [comment]
Check now

**Review by RavinduSachintha — APPROVED** [review]

**Comment by RavinduSachintha** [comment]
@all-contributors please add @forsas  for code and doc

**Comment by RavinduSachintha** [comment]
@forsas thank you for your contribution. keep it up. :+1: and make sure to star this repository. :wink:

**Pull request merged**
