### PR TITLE
Linear Search in Python3

### LINKED ISSUE #774: Linear Search in Python3
This is an open issue for the Linear Search algorithm implementation in Python3. If you wish to contribute, just make some noise and we will assign you.

### PR DESCRIPTION
**Pull request by GetsugaTenzo**
Added {Linear Search} [{ Python3 }]
I have created the linear search in python 3 (linear_search.py) for both integer and non-integer elements.

---

**Fixes #774  **

By submitting this pull request I confirm I've read and complied with the below declarations.

- [x]  I have read the [Contribution guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md) 
and I am confident that my PR reflects them.

-   I have followed the [coding guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#cs) 
for this project.

-   My code follows the [skeleton code structure](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#sample).

-   This pull request has a descriptive title. 
For example, `Added {Algorithm/DS name} [{Language}]`, not `Update README.md` or `Added new code`.

-   This pull request shall only be merged once the build passes.

-    I have mentioned the issue number correctly (with hyperlink) in this pull request description.

### CODE REVIEW

**Comment by GetsugaTenzo** [comment]
Hai. kindly review my pull request Let me know if I am to add anything.

**Review by RavinduSachintha — COMMENTED** [review]
@GetsugaTenzo there is a trailing whitespace issue that captured to our code analyzer. pls resolve it and update this PR.

**Comment by GetsugaTenzo** [comment]
Hai. I have removed the trailing whitespaces. Kindly review.

**Comment by GetsugaTenzo** [comment]
Hi. I have removed trailing whitespaces. Kindly review.

**Pull request closed without merging**
