### PR TITLE
Fixed Java Performance Issue  with System::arraycopy

### PR DESCRIPTION
**Pull request by talhacevik**
This PR fixed for this issue https://github.com/FOSS-UCSC/FOSSALGO/issues/613#L46

### CODE REVIEW

**Comment by Danushka96** [comment]
Hi @talhacevik 
We can't accept this PR because you are not assigned to any issue

**Comment by talhacevik** [comment]
> Hi @talhacevik
> We can't accept this PR because you are not assigned to any issue

Hi @Danushka96, thanks for your warning. I attached the related issue.

**Review by Danushka96 — APPROVED** [review]

**Comment by Danushka96** [comment]
@all-contributors please add @talhacevik  for code

**Comment by talhacevik** [comment]
> @all-contributors please add @talhacevik for code

Thanks :)

**Pull request merged**
