### PR TITLE
Added BinSort.java

### LINKED ISSUE #429: Bin-Sort in Java
This is an open issue for bin sorting algorithm implementation in Java. If you wish to contribute, just make some noise and we will assign you.

### PR DESCRIPTION
**Pull request by SravanthiKaki**
Added Bin Sort implementation in Java

**Hi!**  
Thanks for considering contributing to this ever-growing list of algorithm and data structure implementations.
Your contribution is valuable. Use the follow template for creating Pull Requests
---

**Fixes #429 **

By submitting this pull request I confirm I've read and complied with the below declarations.

-   [1 ] I have read the [Contribution guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md) 
and I am confident that my PR reflects them.

-   [1 ] I have followed the [coding guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#cs) 
for this project.

-   [1 ] My code follows the [skeleton code structure](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#sample).

-   [ 1] This pull request has a descriptive title. 
For example, `Added {Algorithm/DS name} [{Language}]`, not `Update README.md` or `Added new code`.

-   [1 ] This pull request shall only be merged once the build passes.

-   [1 ] I have mentioned the issue number correctly (with hyperlink) in this pull request description.

### CODE REVIEW

**Comment by Danushka96** [comment]
Hi @SravanthiKaki 
There's an issue with the file name, 
Use **UpperCamel** or **simple letters with an underscore**

**Comment by SravanthiKaki** [comment]
> Hi @SravanthiKaki
> There's an issue with the file name,
> Use **UpperCamel** or **simple letters with an underscore**

I made the changes and all checks have passed. Can you please review it?

**Review by RavinduSachintha — APPROVED** [review]

**Comment by RavinduSachintha** [comment]
@SravanthiKaki would you be able to add your contribution to the algorithm chart in the main README file? Don't change anything else. You just need to push your changes here.

**Comment by RavinduSachintha** [comment]
@all-contributors please add @SravanthiKaki for code and doc

**Comment by RavinduSachintha** [comment]
@SravanthiKaki Thank you for your contribution. Keep it up. :+1: And make sure to star this repo :wink:

**Pull request merged**
