### PR TITLE
coin change added in GoLang.

### PR DESCRIPTION
**Pull request by sg-4**
**Fixes #*https://github.com/FOSS-UCSC/FOSSALGO/issues/572*

By submitting this pull request I confirm I've read and complied with the below declarations.

-   [x] I have read the [Contribution guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md) 
and I am confident that my PR reflects them.

-   [x] I have followed the [coding guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#cs) 
for this project.

-   [x] My code follows the [skeleton code structure](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#sample).

-   [x] This pull request has a descriptive title. 
For example, `Added {Algorithm/DS name} [{Language}]`, not `Update README.md` or `Added new code`.

-   [x] This pull request shall only be merged once the build passes.

-   [x] I have mentioned the issue number correctly (with hyper-link) in this pull request description.

### CODE REVIEW

**Comment by RavinduSachintha** [comment]
@sg-4 can you add this contribution to the algorithm chart in the readme file?

**Comment by sg-4** [comment]
done

**Review by Danushka96 — APPROVED** [review]

**Comment by Danushka96** [comment]
@all-contributors please add @sg-4 for code and doc

**Comment by Danushka96** [comment]
Hi @sg-4 
Thanks for your contribution! keep it up!

**Pull request merged**
