### PR TITLE
Added Linear Search in Javascript 

### PR DESCRIPTION
**Pull request by LaxmiNyamagoud**
**Hi!**  
Thanks for considering for contributing to this ever-growing list of algorithm and data structure implementations.
Your contribution is valuable. Use the follow template for creating PRs. (Delete this part)
---

**Fixes #{776}**

By submitting this pull request I confirm I've read and complied with the below declarations.

-   [x] I have read the [Contribution guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md) 
and I am confident that my PR reflects them.

-   [x] I have followed the [coding guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#cs) 
for this project.

-   [x] My code follows the [skeleton code structure](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#sample).

-   [x] This pull request has a descriptive title. 
For example, `Added {Algorithm/DS name} [{Language}]`, not `Update README.md` or `Added new code`.

-   [x] This pull request shall only be merged once the build passes.

-   [x] I have mentioned the issue number correctly (with hyper-link) in this pull request description.

### CODE REVIEW

**Comment by Danushka96** [comment]
Hi @LaxmiNyamagoud 
Shall we make a clear PR? because this one contains some older files,

**Comment by Danushka96** [comment]
Hi @LaxmiNyamagoud 
Can you update the Main Readme.md file?

**Comment by LaxmiNyamagoud** [comment]
> Hi @LaxmiNyamagoud
> Can you update the Main Readme.md file?

ok

**Comment by LaxmiNyamagoud** [comment]
> Hi @LaxmiNyamagoud
> Can you update the Main Readme.md file?

Main Readme.md file is already there

**Comment by Danushka96** [comment]
Can you update with a tick to the algorithm table in the raw of the algorithm you implemented?

**Comment by LaxmiNyamagoud** [comment]
> Can you update with a tick to the algorithm table in the raw of the algorithm you implemented?

ok

**Review by Danushka96 — APPROVED** [review]

**Comment by LaxmiNyamagoud** [comment]
Thanks!

**Pull request merged**
