### PR TITLE
Added insertion_sort.cpp file for the Insertion sort in c++ by jeewan…

### PR DESCRIPTION
**Pull request by Jeewantha95**
…tha95

**Hi!**  
Thanks for considering for contributing to this ever-growing list of algorithm and data structure implementations.
Your contribution is valuable. Use the follow template for creating PRs. (Delete this part)
---

**Fixes #79 #634}**

By submitting this pull request I confirm I've read and complied with the below declarations.

-   [x] I have read the [Contribution guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md) 
and I am confident that my PR reflects them.

-   [x] I have followed the [coding guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#cs) 
for this project.

-   [x] My code follows the [skeleton code structure](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#sample).

-   [x] This pull request has a descriptive title. 
For example, `Added {Algorithm/DS name} [{Language}]`, not `Update README.md` or `Added new code`.

-   [x] This pull request shall only be merged once the build passes.

-   [x] I have mentioned the issue number correctly (with hyper-link) in this pull request description.

### CODE REVIEW

**Comment by Danushka96** [comment]
Hi @Jeewantha95 
Can you update the main readme with your algorithm? 
Just put a tick to the algorithm table.
Send the commit to the same PR, 
Thanks

**Review by Danushka96 — APPROVED** [review]

**Comment by Jeewantha95** [comment]
@Danushka96 Okay bro. I will do it

**Comment by Danushka96** [comment]
Hi @Jeewantha95 
Are you working on this? It's just a single line of code to edit,

**Comment by Jeewantha95** [comment]
@Danushka96  yes. I will fix this as soon as possible . i will do it before tommorow

**Comment by RavinduSachintha** [comment]
@Jeewantha95 we can merge this to our main repository if you can add this contribution to the readme file soon. Thank you. :+1:

**Pull request closed without merging**
