### PR TITLE
Added Insertion Sort Python 3

### PR DESCRIPTION
**Pull request by liamm91**
**Hi!**  
Thanks for considering for contributing to this ever-growing list of algorithm and data structure implementations.
Your contribution is valuable. Use the follow template for creating PRs. (Delete this part)
---

**Fixes #{ISSUE_NUMBER}**

By submitting this pull request I confirm I've read and complied with the below declarations.

-   [x] I have read the [Contribution guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md) 
and I am confident that my PR reflects them.

-   [x] I have followed the [coding guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#cs) 
for this project.

-   [x] My code follows the [skeleton code structure](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#sample).

-   [x] This pull request has a descriptive title. 
For example, `Added {Algorithm/DS name} [{Language}]`, not `Update README.md` or `Added new code`.

-   [x] This pull request shall only be merged once the build passes.

-   [x] I have mentioned the issue number correctly (with hyper-link) in this pull request description.

### CODE REVIEW

**Comment by liamm91** [comment]
This if for issue #632

**Comment by RavinduSachintha** [comment]
@liamm91 would you be able to add this contribution to the algorithm chart in readme file? don't change anything else. :+1:

**Review by RavinduSachintha — APPROVED** [review]

**Comment by liamm91** [comment]
Done, I added it to the README.md file in my repo

**Comment by Danushka96** [comment]
@all-contributors please add @liamm91 for code and doc

**Comment by Danushka96** [comment]
Hi @liamm91 
Thanks for your contribution!

**Pull request merged**
