### PR TITLE
coin change added in Golang

### LINKED ISSUE #572: Coin Change Problem in Golang
This is an open issue for the Coin Change Problem algorithm implementation in Golang. If you wish to contribute, just make some noise and we will assign you.

### PR DESCRIPTION
**Pull request by sg-4**
**Fixes #572 }**

By submitting this pull request I confirm I've read and complied with the below declarations.

-   [x] I have read the [Contribution guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md) 
and I am confident that my PR reflects them.

-   [x] I have followed the [coding guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#cs) 
for this project.

-   [x] My code follows the [skeleton code structure](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#sample).

-   [x] This pull request has a descriptive title. 
For example, `Added {Algorithm/DS name} [{Language}]`, not `Update README.md` or `Added new code`.

-   [x] This pull request shall only be merged once the build passes.

-   [x] I have mentioned the issue number correctly (with hyper-link) in this pull request description.

### CODE REVIEW

**Comment by Danushka96** [comment]
Hi @sg-4 
Your commit has 2 changes, Both Golang and python implementations, we can't accept such PRs

**Comment by sg-4** [comment]
Oh okay. Is there any way i can change it?

**Comment by Danushka96** [comment]
Hi @sg-4 
Remove the Python implementation and resolve the conflicted files(Readme.md has a conflict)

**Comment by sg-4** [comment]
Ohhh okay
Thanks a lot!!

**Comment by Danushka96** [comment]
Hi @sg-4 
Resolve the conflicts

**Comment by sg-4** [comment]
I am sorry I am unable to resolve the conflicts.

**Comment by sg-4** [comment]
I cannot create a PR with only the golang implementation.

**Comment by Danushka96** [comment]
Hi @sg-4 
You have three options,
1. Delete the python implementation,
2. Create a new branch from master or
3. Add the implementation to a freshly forked repo

**Comment by sg-4** [comment]
ok thank you so much. I will do the required.

**Comment by sg-4** [comment]
I made a new pull request by forking the repo again. I am thus closing this request. Thank you so much for your help. Its because of this community that open source is as nice as it is.

**Pull request closed without merging**
