### PR TITLE
Added Dijkstra Algorithm [C]

### LINKED ISSUE #531: Dijkstra Algorithm in C
This is an open issue for the Dijkstra Algorithm algorithm implementation in C. If you wish to contribute, just make some noise and we will assign you.

### PR DESCRIPTION
**Pull request by shouvikch97**
**Hi!**  
Thanks for considering for contributing to this ever-growing list of algorithm and data structure implementations.
Your contribution is valuable. Use the follow template for creating PRs. (Delete this part)
---

**Fixes #531 **

By submitting this pull request I confirm I've read and complied with the below declarations.

-   [x] I have read the [Contribution guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md) 
and I am confident that my PR reflects them.

-   [x] I have followed the [coding guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#cs) 
for this project.

-   [x] My code follows the [skeleton code structure](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#sample).

-   [x] This pull request has a descriptive title. 
For example, `Added {Algorithm/DS name} [{Language}]`, not `Update README.md` or `Added new code`.

-   [x] This pull request shall only be merged once the build passes.

-   [x] I have mentioned the issue number correctly (with hyper-link) in this pull request description.

### CODE REVIEW

**Review by Danushka96 — APPROVED** [review]

**Comment by Danushka96** [comment]
Hi @shouvikch97 
Can you update the main Readme file with your algorithm? just add a tick to the table.
Send the commit to this PR.
Thanks

**Comment by shouvikch97** [comment]
I have updated the Readme.md..but I am not sure what to do next.I am new to
Git and this is only my 2nd open source contribution.Any kind of help would
be appreciated.
Thank you

**Comment by Danushka96** [comment]
Hi @shouvikch97 
Great! Do these simple steps,
 
1. Commit the changes
2. Push it to your repo

It will appear here. Thanks

**Comment by shouvikch97** [comment]
Thanks.
I did as you said.
I hope it helps.

**Comment by RavinduSachintha** [comment]
@shouvikch97 good job. Would you be able to add this contribution to the algorithm chart in the main readme file? Don't change anything else.

**Comment by shouvikch97** [comment]
I think I already did that(added the tick mark to the C Column of Dijkstra).If you are requesting for something else, could you please clarify?

**Comment by Danushka96** [comment]
Hi @shouvikch97 
I can't see the changes here, Did you push the changes?

**Comment by shouvikch97** [comment]
Yes I pushed it to the same branch where I had first pushed the code.I did
not create any separate branch.

**Comment by Danushka96** [comment]
@shouvikch97 
No, Still no changes, Did you push the changes to the `add-dijkstra-c` branch?

**Comment by shouvikch97** [comment]
Error
Could you please tell me where I am going wrong?

**Comment by Danushka96** [comment]
Hi @shouvikch97 
Good job! Hope you learned some stuff! 
Thanks for your contribution!

**Comment by Danushka96** [comment]
@all-contributors please add @shouvikch97 for code and doc

**Comment by shouvikch97** [comment]
Yes it was fun and I did learn quite a lot from it.
Thank you 👍

**Pull request merged**
